baseURL: https://kensoz.github.io
title: BLOG
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true
copyright: "©︎ 2023 renhou"
defaultContentLanguage: cn

languages:
  cn:
    languageName: "简体中文"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: GitHub
          url: https://github.com/adityatelange/hugo-PaperMod/wiki/

  ja:
    languageName: "日本語"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: GitHub
          url: https://github.com/kensoz/personal-blog

params:
  description: "blog"
  author: renhou

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

  homeInfoParams:
    Title: "Lai"
    Content: >
      Welcome to demo of Lai !

  socialIcons:
    - name: github
      url: "https://github.com/kensoz/personal-blog"

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
